#!/bin/bash

# iOS Provisioning Profile Setup Script
# This script helps set up iOS code signing for MediLink

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$SCRIPT_DIR"

echo "======================================"
echo "MediLink iOS Provisioning Setup"
echo "======================================"
echo ""

# Variables to configure
read -p "Apple Team ID (from Apple Developer): " TEAM_ID
read -p "Bundle Identifier (e.g., com.archana.medilink): " BUNDLE_ID
read -p "Bundle Identifier for extensions (optional, press Enter to skip): " BUNDLE_ID_EXTENSION

echo ""
echo "Which provisioning profile type do you want to set up?"
echo "1) Development"
echo "2) Distribution (App Store)"
echo "3) Ad Hoc (Testing)"
read -p "Select (1-3): " PROFILE_TYPE

case $PROFILE_TYPE in
    1)
        PROFILE_NAME="MediLink Development"
        PROFILE_TYPE_NAME="development"
        ;;
    2)
        PROFILE_NAME="MediLink App Store"
        PROFILE_TYPE_NAME="distribution"
        ;;
    3)
        PROFILE_NAME="MediLink Ad Hoc"
        PROFILE_TYPE_NAME="ad-hoc"
        ;;
    *)
        echo "Invalid selection"
        exit 1
        ;;
esac

echo ""
echo "Steps to complete iOS provisioning:"
echo ""
echo "1. Open Apple Developer Portal (https://developer.apple.com)"
echo ""
echo "2. Go to Certificates, Identifiers & Profiles section"
echo ""
echo "3. Create/Renew Certificate:"
echo "   - Click 'Certificates' > 'Add' (if needed)"
echo "   - Select 'iOS App Development' or 'Apple Distribution'"
echo "   - Follow the prompts to upload a certificate signing request"
echo "   - Download the .cer file and double-click to install"
echo ""
echo "4. Register App ID:"
echo "   - Click 'Identifiers' > 'App IDs' > 'Add' (if not exists)"
echo "   - Bundle ID: $BUNDLE_ID"
echo "   - Capabilities: Push Notifications, Sign in with Apple"
echo ""
if [ ! -z "$BUNDLE_ID_EXTENSION" ]; then
    echo "5. Register App ID Extension:"
    echo "   - Bundle ID: $BUNDLE_ID_EXTENSION"
    echo ""
fi
echo "6. Register Devices:"
echo "   - Click 'Devices' > 'Add'"
echo "   - Enter your device identifiers (UDID)"
echo "   - To get UDID: Xcode > Devices > Select device > Copy UDID"
echo ""
echo "7. Create Provisioning Profile:"
echo "   - Click 'Provisioning Profiles' > 'Add'"
echo "   - Select profile type: $PROFILE_TYPE_NAME"
echo "   - Select App ID: $BUNDLE_ID"
echo "   - Select certificates"
echo "   - Select devices (for development/ad-hoc)"
echo "   - Profile name: $PROFILE_NAME"
echo "   - Download and double-click to install"
echo ""
echo "8. Update Xcode Project:"
echo "   - Open ios/Runner.xcodeproj/project.pbxproj"
echo "   - Search and replace DEVELOPMENT_TEAM with: $TEAM_ID"
echo "   - In Xcode: Runner > Build Settings"
echo "   - Search for 'Signing' > Provisioning Profile"
echo "   - Select the profile you created"
echo ""

echo "9. Verify Setup in Xcode:"
read -p "Press Enter when provisioning profiles are installed..."

cd "$PROJECT_DIR"

PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning\ Profiles"

echo ""
echo "Checking installed provisioning profiles..."
if [ -d "$PROFILES_DIR" ]; then
    echo "Found provisioning profiles in: $PROFILES_DIR"
    echo ""
    ls -la "$PROFILES_DIR" | grep -i medilink || echo "No MediLink profiles found yet"
else
    echo "Profiles directory not found at expected location"
fi

echo ""
echo "To update the Xcode project with Team ID and bundle ID:"
echo ""
echo "1. Update Team ID in Xcode:"
echo "   open ios/Runner.xcodeproj"
echo "   Then Set Build Settings > DEVELOPMENT_TEAM = $TEAM_ID"
echo ""
echo "2. Update Bundle Identifier:"
echo "   Build Settings > PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID"
echo ""

# Create a configuration file
CONFIG_FILE="$SCRIPT_DIR/provisioning_config.txt"
cat > "$CONFIG_FILE" << EOF
# iOS Provisioning Profile Configuration
# Generated by setup script

TEAM_ID=$TEAM_ID
BUNDLE_ID=$BUNDLE_ID
BUNDLE_ID_EXTENSION=$BUNDLE_ID_EXTENSION
PROFILE_TYPE=$PROFILE_TYPE_NAME
PROFILE_NAME=$PROFILE_NAME

# Certificate Details
# - Certificate Serial Number: (Find in Keychain Access)
# - Expiration Date: (From Apple Developer Portal)

# Device UDIDs for testing
# Format: UUID (one per line)
# Example: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
EOF

echo ""
echo "✅ Configuration saved to: $CONFIG_FILE"
echo ""
echo "Next steps:"
echo "1. Complete the provisioning profile setup on Apple Developer Portal"
echo "2. Install provisioning profiles in Xcode"
echo "3. Update TEAM_ID in ios/Runner.xcodeproj"
echo "4. Run: flutter clean && flutter pub get"
echo "5. Test with: flutter run -d 'iOS physical device'"
